AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  demo-app
  Sample SAM Template for demo-app

Globals:
  Function:
    Timeout: 3

Resources:
  DemoWebsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketName: YOUR_BUCKET_NAME

  BucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
     PolicyDocument:
       Id: DemoPolicy
       Version: 2012-10-17
       Statement:
         - Sid: PublicReadForGetBucketObjects
           Effect: Allow
           Principal: "*"
           Action: "s3:GetObject"
           Resource: !Join
             - ""
             - - "arn:aws:s3:::"
               - !Ref DemoWebsite
               - /*
     Bucket: !Ref DemoWebsite

  DemoDistribution:
   Type: "AWS::CloudFront::Distribution"
   Properties:
     DistributionConfig:
       ViewerCertificate:
         AcmCertificateArn: !Ref DemoCertificate
         SslSupportMethod: sni-only
       Aliases:
         - YOUR_ALIAS
       DefaultCacheBehavior:
         ViewerProtocolPolicy: redirect-to-https
         TargetOriginId: YOUR_BUCKET_NAME.s3-website-YOUR_REGION.amazonaws.com
         DefaultTTL: 0
         MinTTL: 0
         MaxTTL: 0
         ForwardedValues:
           QueryString: false
       Origins:
         - DomainName: YOUR_BUCKET_NAME.s3-website-YOUR_REGION.amazonaws.com
           Id: YOUR_BUCKET_NAME.s3-website-YOUR_REGION.amazonaws.com
           CustomOriginConfig:
             OriginProtocolPolicy: http-only
       Enabled: "true"
       DefaultRootObject: index.html

  DemoRoute53Record:
   Type: "AWS::Route53::RecordSetGroup"
   Properties:
     HostedZoneId: YOUR_HOSTED_ZONE_ID
     RecordSets:
       - Name: YOUR_RECORDSET_NAME
         Type: A
         AliasTarget:
           HostedZoneId: Z2FDTNDATAQYW2
           DNSName: !GetAtt DemoDistribution.DomainName

  DemoCertificate:
     Type: AWS::CertificateManager::Certificate
     Properties:
       DomainName: YOUR_DOMAIN_NAME
       ValidationMethod: DNS
